language: php

php:
    - 5.6
    
sudo: false

before_script:
    - pecl install xmldiff
    - composer install --prefer-dist --dev
    - chmod +x ./test-sample-codes.sh
    - git submodule update --recursive
    
script:
    - vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - ./test-sample-codes.sh
